# Generated by Django 2.1.7 on 2019-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='drawCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='loseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='winCount',
            field=models.IntegerField(default=0),
        ),
    ]
