# Generated by Django 2.1.7 on 2019-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0002_auto_20190513_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='firstPlayer',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
