# Generated by Django 2.1.7 on 2019-05-14 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0005_auto_20190514_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
